"""
Generate config.js from .env file for dashboard
This script reads .env file and creates a config.js that the dashboard can use
"""

import os
from pathlib import Path

def generate_config():
    """Generate config.js from .env file"""
    # Get the directory where this script is located
    script_dir = Path(__file__).parent
    
    # Path to .env file
    env_file = script_dir / '.env'
    config_file = script_dir / 'config.js'
    
    # Read .env file
    supabase_url = None
    supabase_key = None
    
    if env_file.exists():
        print(f"Reading .env file: {env_file}")
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    if '=' in line:
                        key, value = line.split('=', 1)
                        key = key.strip()
                        value = value.strip().strip('"').strip("'")
                        
                        if key == 'SUPABASE_URL':
                            supabase_url = value
                        elif key == 'SUPABASE_KEY':
                            supabase_key = value
    
    # Generate config.js
    config_content = f"""// Auto-generated config from .env file
// DO NOT EDIT THIS FILE MANUALLY - Run generate_config.py instead

const SUPABASE_CONFIG = {{
    url: {repr(supabase_url) if supabase_url else 'null'},
    key: {repr(supabase_key) if supabase_key else 'null'}
}};
"""
    
    with open(config_file, 'w') as f:
        f.write(config_content)
    
    if supabase_url and supabase_key:
        print("Config generated successfully!")
        print(f"   URL: {supabase_url[:30]}...")
        print(f"   Key: {supabase_key[:20]}...")
    else:
        print("Warning: Missing credentials in .env file")
        print("   Make sure SUPABASE_URL and SUPABASE_KEY are set")
    
    print(f"\nConfig file created: {config_file}")

if __name__ == '__main__':
    generate_config()

